---
include:
  - board: nice_nano
    shield: sofle_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano
    shield: sofle_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano
    shield: sofle_dongle
    cmake-args: >
      -DCONFIG_ZMK_SPLIT=y
      -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
      -DCONFIG_ZMK_DISPLAY=n
      -DCONFIG_USB_DEVICE_STACK=y
      -DCONFIG_USB_HID=y
      -DCONFIG_USB_COMPOSITE=n
      -DCONFIG_CONSOLE=n
      -DCONFIG_PRINTK=n

  - board: nice_nano
    shield: settings_reset
