# name: Build ZMK firmware

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

name: Build ZMK firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shield: [sofle_left, sofle_right]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Compilar firmware
        uses: zmkfirmware/zmk-build-action@v3  
        with:
          board: nice_nano                      
          shield: ${{ matrix.shield }}
          zmk-version: "v2025.02"               
          artifact-name: sofle_${{ matrix.shield }}
